### ISSUE TITLE
Minimum password length is 8 characters in Laravel 5.8

### ISSUE THREAD

**Issue by jos-** [caouecs/Laravel-lang#1007]
See https://github.com/laravel/framework/pull/25957

All passwords.php files should be updated. The old default was 6 characters.

**Comment by caouecs** [comment]
Hello,
thank you.

I think to do a branch "laravel-58" for the moment

**Comment by edoc-dokopp** [comment]
> I think to do a branch "laravel-58" for the moment

The interim name is producing dependency problems.

>  arcanedev/laravel-lang 6.0.0 requires caouecs/laravel-lang ~3.0

**Comment by andrey-helldar** [comment]
@edoc-dokopp, maybe use [andrey-helldar/laravel-lang-publisher](https://github.com/andrey-helldar/laravel-lang-publisher) instead arcanedev/laravel-lang?
That package has support for versions 5.3-5.8.
