### ISSUE TITLE
Translation for "This password reset link will expire in :count minutes." missing!

### ISSUE THREAD

**Issue by Hans4221** [caouecs/Laravel-lang#1022]
I use your files to translate the laravel basic things to german. And I noticed that in de.json (and other) the key "This password reset link will expire in :count minutes.": is missing.

I saw it by testing the reset password email.

I'm not so deep in Laravel yet and if that's normal then I apologize for the message.

For me I added to de.json:
"This password reset link will expire in :count minutes.": "Dieser Link zum Zurücksetzen des Passworts läuft in :count Minuten ab.",

**Comment by caouecs** [comment]
Hello,
yes, see https://github.com/caouecs/Laravel-lang/blob/master/todo.md#de

Can you do a pull request ?
