### ISSUE TITLE
目前发布的3.0.60版本并没有解决zh-CN.json格式的问题，希望发布一个3.0.61版本。谢谢。

### ISSUE THREAD

**Issue by ChenRuihua** [caouecs/Laravel-lang#1027]
https://github.com/caouecs/Laravel-lang/blob/274e80d8ce28771fb56c77742b8b5d12bdc8fa21/json/zh-CN.json#L46

**Comment by crisslin** [comment]
Laravel-lang/json/zh-CN.json
Line 46，尾巴少了逗号，3.0未修复。

**Comment by overtrue** [comment]
@caouecs Plz make a new release for the fixed bug: https://github.com/caouecs/Laravel-lang/commit/bd37d4d40963d8154d0819c719cab21a69d62396

**Comment by caouecs** [comment]
done

**Comment by overtrue** [comment]
:+1:

Fred Delrieu <notifications@github.com>于2019年3月15日 周五上午1:25写道：

**Comment by overtrue** [comment]
@ChenRuihua 请关掉此 issue.
