### ISSUE TITLE
Array alignment question

### ISSUE THREAD

**Issue by ukadev** [caouecs/Laravel-lang#1044]
Hi there!
I just would like to ask about the array formating. I'm looking to the package and I noticed that in some update the arrays have changed to be aligned instead of natural size array key => value.
IMO it's better to maintain the natural size alignment for easy reading and because if you add a new larger key you have to change the whole file, and it may cause conflicts.

What do you think about it?

Regards.

**Comment by andrey-helldar** [comment]
Alignment of elements improves the reading of the array by man. Concerning conflicts, before sending the PR you need to update your code. In other cases, conflicts are impossible.

See also #977, #460 and #477.

**Comment by ukadev** [comment]
Thank for the response and sorry for the duplicated topic. 
IMO the alignment doesn't improve the reading of the array. It's easier and faster follow the line separated by an space than by <for example> two or three tabs. It's just logic: more space, more difficult to read. 
If you want to see a beauty code it can be perfect, like inside a table, but it's not what I want when I code, I prefer to have a uglier but readable code.
if you need to jump with your eyes ir order to follow the same line, sometimes it can be easy to "jump" directly to another line.

By the way, I was just curious about it.

**Comment by andrey-helldar** [comment]
Probably someone like that. Personally, it's easier and more convenient for me to read aligned code. Without alignment, for me personally, the code looks like a pile of dung.

Perhaps the author of the package does not agree with me.

Example:

![thumb](https://cloud.githubusercontent.com/assets/779534/10904104/c25582be-8210-11e5-9741-4d8a15a26491.jpg)

**Comment by andrey-helldar** [comment]
In my opinion, if you read the code as a book, then yes, the indents are in the way. But if you read the code as a code, the lack of indentation is confusing. The eyes see the plot and do not immediately understand this key name or the text has already begun.

**Comment by ukadev** [comment]
Oh, I see, your ide show a line of dots to maintain the line between the key and the value of the value. In phpstorm I don't see that (at least by default). 

Well, I think I don't need to read the code as a book, and the keys are simply at the begining of the line. It's not really dificult to see tham (at least for me), that's why the arrow has a different colour.  Even the auto-formating tool of phpstorm removes the alignment of these arrays with the psr1-psr2.

But again, and as I can see, it's something something particular, something based on each own point of view and not in an standard.

**Comment by andrey-helldar** [comment]
This is a screenshot from #460. I use a light theme for phpStorm, but now I can’t show it because I am in another country.

The psr-2 standard allows both types, but which one depends on the developer. As they say in our country, "all markers are different in taste and color." 🙂

**Comment by andrey-helldar** [comment]
I have no points in the code in the lines. In order not to be confused which element belongs to which line, I try to break the lines into logical blocks.
Example: 

![S90407-13240018](https://user-images.githubusercontent.com/10347617/55682368-3e9e1200-593b-11e9-8566-a27852c1bf83.jpg)

This makes it much easier to read an array than with solid text.
