### ISSUE TITLE
Serbian country code issue

### ISSUE THREAD

**Issue by arnyee** [caouecs/Laravel-lang#1051]
Hello, The Serbian folder nem (sr) is not correct, the correct country code is rs!

**Comment by caouecs** [comment]
Hello,
we respect the iso 639-1 and it's sr

**Comment by petercoles** [comment]
@caouecs

Great package. And right answer on this issue, though for the wrong reasons.

It is true that the ISO 639-1 code for Serbian is sr whereas the ISO 3166 code is rs, which I suspect prompts this issue. However, you also use pt-BR, zc-CN, zh-HK and zh-TW, which aren't ISO 639-1 codes.

I'd suggest the standard that actually matters here is the PHP locale codes. For that the 14 or so flavours of Serbian start "sr" as you have it, so won't break anybody app if they include it.

**Comment by caouecs** [comment]
iso 3166 is for country, not language
