### ISSUE TITLE
Publish a Stable Version for Laravel 5.8

### ISSUE THREAD

**Issue by tanmuhittin** [caouecs/Laravel-lang#1055]
I am preparing a PR for https://github.com/barryvdh/laravel-translation-manager in order to publish Laravel base lang files when a new locale added. I am planing to use this repository via https://github.com/andrey-helldar/laravel-lang-publisher/pull/3 but https://github.com/barryvdh/laravel-translation-manager requires minimum stability:stable. So I need a stable version of this package for Laravel 5.8

**Comment by andrey-helldar** [comment]
I support!

In my opinion, splitting versions by branch name is not a very good solution.

Alternatively, a major version can be used as a stable branch.

For example:
```
^3.0 >> Laravel 5.7 and below
^4.0 >> Laravel 5.8+
```

**Comment by caouecs** [comment]
oki dokki

I will do it tomorrow

**Comment by andrey-helldar** [comment]
I am sure that you, @caouecs, can do it without me, but anyway I will post a picture here 😊

![2019-04-15_22-53-19](https://user-images.githubusercontent.com/10347617/56161043-4b70d480-5fd1-11e9-9075-4306dade2922.png)

**Comment by andrey-helldar** [comment]
@caouecs, I prepared the necessary changes for both branches ☝ 😊

**Comment by andrey-helldar** [comment]
@caouecs, thank you!

@tanmuhittin, use version [^1.5](https://github.com/andrey-helldar/laravel-lang-publisher/releases/tag/v1.5.0) version for a stable Laravel 5.8 and above or [^1.0](https://github.com/andrey-helldar/laravel-lang-publisher) for Laravel 5.3-5.8 inclusive.
