### ISSUE TITLE
[RO] Wrong translation in validation.php

### ISSUE THREAD

**Issue by marioene** [caouecs/Laravel-lang#1091]
Hi,

Wrong translation in validation.php for romanian language.

File Laravel-lang/src/ro/validation.php 

line 103:

    'same'                 => 'Câmpul :attribute și :other trebuie să fie identice.',

should be:

    'same'                 => 'Câmpurile :attribute și :other trebuie să fie identice.',

Argument:

'Câmpul' (Field in english) is for a singular field (like :attribute). 

'Câmpurile' (Fields in english) is for plural fields, because you have there 2 fields variable names (:attribute and :other).

**Comment by caouecs** [comment]
Hello,
can you do a pull request ?
