### ISSUE TITLE
Laravel 6.0 removed deprecated language line

### ISSUE THREAD

**Issue by andrey-helldar** [caouecs/Laravel-lang#1104]
Laravel 6.0 is coming soon.
You see this https://github.com/laravel/laravel/pull/5074?

I [prepared a commit for PR](https://github.com/andrey-helldar/Laravel-lang/commit/7c01c71e79cf4d9a64ca4344c8eaba061c361f64) (+ [fix codestyle](https://github.com/andrey-helldar/Laravel-lang/commit/d351d2f8b9f87f06412884203de2752ffdf028cf)) for all languages, but you can’t send it to the master. The best solution would be to create a `laravel60` branch and send the PR to it.

What do you think about it?

**Comment by caouecs** [comment]
For the moment, it's not mandatory to delete it, the package will stay compatible with Laravel 5 and 6 ;)

**Comment by andrey-helldar** [comment]
Hmm... 😑
Yea! 👍
