### ISSUE TITLE
Does not use language set as locale

### ISSUE THREAD

**Issue by dvlden** [caouecs/Laravel-lang#1178]
Either README is not clear enough or I'm doing something wrong?
To my understanding, it should be working as:

1. Install package
2. Set locale and fallback_locale in the config/app
3. It works

If so, it does not... I get English messages instead of messages in `sr` locale that I specified.
Further, in the README file, I saw that there's a mention of copying dirs/files that we need? Why is it a package then? (maybe this is just an old and outdated message)

Please, let me know what's wrong. Using Laravel 6.x!

**Comment by andrey-helldar** [comment]
@dvlden, this package contains only translation files that need to be manually transferred to the resource folder of your project.

Or use the https://github.com/andrey-helldar/laravel-lang-publisher package to automatically install and update languages.
