### ISSUE TITLE
Irrelevant project description

### ISSUE THREAD

**Issue by andrey-helldar** [caouecs/Laravel-lang#1221]
**Now:**
![2020-03-14_01-08-28](https://user-images.githubusercontent.com/10347617/76662861-5a208c80-6590-11ea-9c53-b003e26b4ba4.jpg)

**Need:**
`List of 74 languages for Laravel 5, 6 and 7`

(73 in the `src` directory + `en`)

**Comment by caouecs** [comment]
75 ;)
