### ISSUE TITLE
problem with lang.json

### ISSUE THREAD

**Issue by daltar** [caouecs/Laravel-lang#1226]
Hello,

I am currently using the file json/fr.json from your repository.
Everything is translated, except for this line :

    "If you’re having trouble clicking the \":actionText\" button, copy and paste the URL below\ninto your web browser: [:displayableActionUrl](:actionURL)": "Si vous avez des problèmes en cliquant sur le bouton \":actionText\", faites un copié/collé de l'url ci-dessous dans votre navigateur :\n [:displayableActionUrl](:actionURL)".

do you have any idea for this?

**Comment by daltar** [comment]
I am using laravel 6.5.2 btw

**Comment by andrey-helldar** [comment]
You can fork this repository, modify file [json/fr.json](https://github.com/caouecs/Laravel-lang/blob/master/json/fr.json) and send PR.

**Comment by caouecs** [comment]
For Laravel 6, you don't need the line with *displayableActionUrl* ? It's for Laravel 7, is not it ?

**Comment by idhamperdameian** [comment]
Hi this issue is correct, the translation changing since Laravel 6.x. Please check here https://github.com/laravel/framework/blob/6.x/src/Illuminate/Notifications/resources/views/email.blade.php#L55

For Laravel prior to 6.x the translations is good.

So I think all *.json file need to modified for Laravel 6.x dan Laravel 7.x

**Comment by idhamperdameian** [comment]
> For Laravel 6, you don't need the line with _displayableActionUrl_ ? It's for Laravel 7, is not it ?

The line _displayableActionUrl_ affected since Laravel 6.x. Please check here https://github.com/laravel/framework/blob/6.x/src/Illuminate/Notifications/resources/views/email.blade.php#L55

**Comment by Daniel-Mendes** [comment]
I think it's because laravel don't pass the actionURL only actionText.

File: [email.blade.php](https://github.com/laravel/framework/blob/7.x/src/Illuminate/Notifications/resources/views/email.blade.php)

```php
@lang(
    "If you’re having trouble clicking the \":actionText\" button, copy and paste the URL below\n".
    'into your web browser:',
    [
        'actionText' => $actionText,
    ]
) <span class="break-all">[{{ $displayableActionUrl }}]({{ $actionUrl }})</span>

```

**Comment by Daniel-Mendes** [comment]
D’ailleurs c'est copier/coller et pas copié/collé

**Comment by caouecs** [comment]
je dirais plutôt copiez et collez

**Comment by robertgarrigos** [comment]
This line:

```
If you’re having trouble clicking the \":actionText\" button, copy and paste the URL below\ninto your web browser: [:displayableActionUrl](:actionURL)
```

should be changed to:

```
If you’re having trouble clicking the \":actionText\" button, copy and paste the URL below\ninto your web browser:
```

**Comment by olsza** [comment]
> This line:
> 
> ```
> If you’re having trouble clicking the \":actionText\" button, copy and paste the URL below\ninto your web browser: [:displayableActionUrl](:actionURL)
> ```
> 
> should be changed to:
> 
> ```
> If you’re having trouble clicking the \":actionText\" button, copy and paste the URL below\ninto your web browser:
> ```

I noticed the same error as you @robertgarrigos in the translation for PL, I corrected the same problem, and only now I noticed that you wrote it here;)

**Comment by caouecs** [comment]
Sorry for the lag

So, I delete "[:displayableActionUrl](:actionURL)" everywhere ?

**Comment by robertgarrigos** [comment]
just delete `[:displayableActionUrl](:actionURL)`

**Comment by caouecs** [comment]
done

**Comment by olsza** [comment]
thx for updating all files :)
