### ISSUE TITLE
支持找到__('')方法中的字符，并转成语言包吗？

### ISSUE THREAD

**Issue by neatstudio** [caouecs/Laravel-lang#1259]
如题。比如有一些代码是先写的，类似于mock一样，在写的时候并没有相应的语言包设置。
比如就写了不少的$name = __('name');或者 $ame = __('admin.name');
能否根据这个生成相应的 language文件？
比如默认的，就加到zh-CN.json中。有前缀的创建相应的文件，并写进去？

**Comment by caouecs** [comment]
Hello,
sorry, but can you translate in english ?

**Comment by neatstudio** [comment]
sorry ,i want send issue to project : overtrue/lang ...
it's my fault.

**Comment by andrey-helldar** [comment]
@neatstudio, 

This is implemented by json localization files.

As far as I know, a package from `overtrue` is not able to work with them. But you can use [another translation manager](https://github.com/andrey-helldar/laravel-lang-publisher#lang-publisher) who knows how to do this.
