### ISSUE TITLE
Login vs Log In

### ISSUE THREAD

**Issue by jeff-h** [caouecs/Laravel-lang#1262]
In our site we prefer to use "Log In" where the term is used as a verb, but doing so eliminates all your lovely translations, because they are only available for "Login".

Is this simply because Laravel itself only uses "Login"? Would you consider adding "Log In" as well? Unfortunately I am too ignorant to know what kind of impact that would have in all the other languages.

**Comment by caouecs** [comment]
Good question... for French, no difference

Your problem is for json ?

**Comment by jeff-h** [comment]
Yes, the json.

**Comment by caouecs** [comment]
Maybe, the easier is to add « log in » in English Json and wait that community translates ;)

**Comment by caouecs** [comment]
@jeff-h ping

**Comment by jeff-h** [comment]
Closing, because this repo is for text that already exists in the Laravel framework, and unfortunately "Log In" and "Log Out" don't.
