### ISSUE TITLE
Proposal: validation-strings without attribute placeholder

### ISSUE THREAD

**Issue by kohlerdominik** [caouecs/Laravel-lang#1268]
Hi

### Issue

By default Laravel always uses the `:attributes`-Placeholder in it's validation strings.
But for example in in Material Design it's recommendet to provide the Error Message right next to the Input field ([Source](https://material.io/components/text-fields)). This kind of makes the `:attribute` a redundancy. While for english, the guessed names may be usuable mostly (not always pretty, but at least usable), for other languages you're basically forced to translate every attribute as well.

For me, it's is especially cumbersome if you have devided front- and backend. You need to maintain the attribute name once in the Frontend _Label_-tag, and once in the Backend, while there's basically no benefit in it.

---
Example how this currently looks like (rule:numeric)
![grafik](https://user-images.githubusercontent.com/18621527/85400838-54f0b780-b559-11ea-9eb8-5f9ccc199255.png)

Example from the same in german or french
![grafik](https://user-images.githubusercontent.com/18621527/85401280-0f80ba00-b55a-11ea-83ca-1e20084723f5.png)
Note how the label is translated, but the `:attribute` would require an extra translation in this case.

---

### Proposed Solution
Within this package, we could start a second series of translations with more generic text, which do not use the `:attribute`-tag in the translated string. So in above examples, it would mean using something like
```
This has to be a number.
Das muss eine Zahl sein.
Il doit s'agir d'un numéro [translation from DeepL]
```

I would be happy to help with this. However, the benefit should be reasonable to others, too, so we can quickly start with a couple of languages like English (by me), German (by me), French, Spanish?

**Comment by caouecs** [comment]
It's a very good idea, we can do another branch with it

Can you do a pull request with english and german translations ? I can do for French

**Comment by kohlerdominik** [comment]
Hi @caouecs 

Thanks for the positive Feedback. I just didn't find time yet, but I'll create the PR next week.
