### ISSUE TITLE
ISO 15897 format of country specific locales

### ISSUE THREAD

**Issue by bjoerne2** [caouecs/Laravel-lang#1269]
On https://laravel.com/docs/7.x/localization it says:

> For languages that differ by territory, you should name the language directories according to the ISO 15897. For example, "en_GB" should be used for British English rather than "en-gb".

Wouldn't it be better to rename the country specific folders, e.g. de-CH -> de_CH?

**Comment by caouecs** [comment]
Good idea, we need to do a new major version ( v7 ), because we brake directory names...

Can you do a pull request ?

**Comment by bjoerne2** [comment]
I created a PR: https://github.com/caouecs/Laravel-lang/pull/1276

**Comment by caouecs** [comment]
Can I have references for language names ? As sr_Cyrl

**Comment by caouecs** [comment]
My problem is for sr_Cyrl, sr_Latn, uz_Cyrl and uz_Latn.

**Comment by andrey-helldar** [comment]
Either I read the technical documentation poorly, or in the description of the [ISO 15897](http://www.open-std.org/jtc1/sc22/wg20/docs/n610.pdf) standard from 1998 there is no mention of the rules for naming language localizations.
Standard ISO 15897 from the 2011 model year is [paid](https://www.iso.org/standard/50707.html) 😐

**Comment by andrey-helldar** [comment]
I may be wrong, but I want to propose to call it this way:
```
de_CH
pt_BR
...
sr_Cyrillic
sr_Latin
uz_Cyrillic
uz_Latin
```

**Comment by caouecs** [comment]
done

Thank you

**Comment by milose** [comment]
If you list the php `Intl` locales, we have a specific list of locales and the naming should be followed.

```php
 collect(ResourceBundle::getLocales(''))->filter(fn($i) => Str::startsWith($i, 'sr'))
=> Illuminate\Support\Collection {#3268
     all: [
       672 => "sr",
       673 => "sr_Cyrl",
       674 => "sr_Cyrl_BA",
       675 => "sr_Cyrl_ME",
       676 => "sr_Cyrl_RS",
       677 => "sr_Cyrl_XK",
       678 => "sr_Latn",
       679 => "sr_Latn_BA",
       680 => "sr_Latn_ME",
       681 => "sr_Latn_RS",
       682 => "sr_Latn_XK",
     ],
   }
```

Meaning that `sr_Latin`, `me`, etc; locale folders you have are invalid.

Note, I am from Montenegro and I use `sr_Latn_ME` nomenclature, when I develop.

**Comment by andrey-helldar** [comment]
@caouecs, Since the `ISO 15897:2011` standard [does not regulate](https://github.com/Laravel-Lang/lang/issues/1269#issuecomment-657100855) the naming of these localizations, I think @milose's proposal is reasonable.

**Comment by caouecs** [comment]
no problem for me

**Comment by andrey-helldar** [comment]
> no problem for me

I created a PR https://github.com/Laravel-Lang/lang/pull/1453, but @LukaLatkovic must review, since he is referent for the `sr_*` languages.

**Comment by LukaLatkovic** [comment]
So, that means that (me) [https://github.com/Laravel-Lang/lang/tree/master/src/me] folder should be renamed to sr_Latn_ME and current sr_Latin and sr_Cyrillic to sr_Latn_RS and sr_Cyrl_RS in that order

**Comment by LukaLatkovic** [comment]
> @caouecs, Since the `ISO 15897:2011` standard [does not regulate](https://github.com/Laravel-Lang/lang/issues/1269#issuecomment-657100855) the naming of these localizations, I think @milose's proposal is reasonable.

This proposal is done by Unicode standard(International Components for Unicode), so maybe we can do locales based on that standard [List of all locales by Unicode](https://icu4c-demos.unicode.org/icu-bin/locexp), [Simple search](https://intl.rmcreative.ru/)

**Comment by milose** [comment]
We are web developers here and this is a Laravel oriented package. With this I mean to say that the directory of the locale should be named in a way so it can be consumed `app()->getLocale()` method.

Laravel workflow is:

1. you set the `'locale'` in `app.php`
2. you use the `<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">` to set the language contained in your HTML output (important for search engines, automatic translations, screen readers etc.
3. you consume other packages with the correct locales like Carbon ([their Lang folder](https://github.com/briannesbitt/Carbon/tree/master/src/Carbon/Lang)) with ease.

Introducing other names, that are not [standardised on the web](https://www.w3.org/International/questions/qa-html-language-declarations#langvalues) means we need to "translate" locale names for other packages, html attributes etc. This is not ideal and the correct nomenclature should be used.

BTW, the translation for Montenegrin language is atrocious. I will make a pull request for the correct translation after this is resolved.

**Comment by andrey-helldar** [comment]
> > @caouecs, Since the `ISO 15897:2011` standard [does not regulate](https://github.com/Laravel-Lang/lang/issues/1269#issuecomment-657100855) the naming of these localizations, I think @milose's proposal is reasonable.
> 
> This proposal is done by Unicode standard(International Components for Unicode), so maybe we can do locales based on that standard [List of all locales by Unicode](https://icu4c-demos.unicode.org/icu-bin/locexp), [Simple search](https://intl.rmcreative.ru/) since Php Intl is based on that
> @caouecs, @andrey-helldar what do you think?

Taylor introduced the ISO 15897:2011 standard into the framework and I think we don't need to violate it. 

If proposals for adjustments do not contradict him, then they can be considered.

**Comment by milose** [comment]
> Taylor introduced the `ISO 15897:2011` standard into the framework and I think we don't need to violate it.

Sauce, please?

**Comment by andrey-helldar** [comment]
> > Taylor introduced the `ISO 15897:2011` standard into the framework and I think we don't need to violate it.
> 
> Sauce, please? @andrey-helldar

You mean [proof](https://laravel.com/docs/8.x/localization#introduction)?

![image](https://user-images.githubusercontent.com/10347617/100476917-edd2c280-30f7-11eb-8c2b-f3605fb75d83.png)

**Comment by milose** [comment]
Thanks @andrey-helldar I missed that.

**Comment by andrey-helldar** [comment]
@milose, a few days ago, we [released](https://github.com/Laravel-Lang/lang/releases/tag/8.0.0) a new major version of the package taking into account these changes.
You can independently monitor the update of files in your project or use a manager. For example, [this one](https://github.com/andrey-helldar/laravel-lang-publisher).

**Comment by caouecs** [comment]
> @milose, a few days ago, we [released](https://github.com/Laravel-Lang/lang/releases/tag/8.0.0) a new major version of the package taking into account these changes.
> You can independently monitor the update of files in your project or use a manager. For example, [this one](https://github.com/andrey-helldar/laravel-lang-publisher).

for example... ;)
