### ISSUE TITLE
Validation-inline in translation publisher

### ISSUE THREAD

**Issue by caouecs** [caouecs/Laravel-lang#1281]
Dear package managers,

in the version 6.1 of Laravel-lang, we added a new file : `validation-inline.php`. It looks like `validation.php` but without `:attribute` ( see [project](https://github.com/caouecs/Laravel-lang/projects/2) ).

I think it should be a good idea to propose at your package users to choose between `validation.php` and `validation-inline.php`.

Actually, I'm working on the update of `todo.php` to support the new file ( see #1278 )

Regards,

caouecs

#### Projects based on this package

* [x] [LaravelLang](https://github.com/ARCANEDEV/LaravelLang) by @arcanedev-maroc  - Translations manager and checker for Laravel.
* [x] [Laravel-lang](https://github.com/overtrue/laravel-lang) by @overtrue  - Command to add languages in your project.
* [x] [laravel-lang-publisher](https://github.com/andrey-helldar/laravel-lang-publisher) by @andrey-helldar  - Easy installation and update of translation files for your project.

**Comment by andrey-helldar** [comment]
Oh! Thank! I will add his support soon. 👍

**Comment by overtrue** [comment]
OK! I will add this support soon. 👍

**Comment by andrey-helldar** [comment]
My package was released 😎
