### ISSUE TITLE
Language names in translation publisher

### ISSUE THREAD

**Issue by caouecs** [caouecs/Laravel-lang#1286]
Dear package managers,

in the future version 7 of Laravel-lang, we will set some sub-directories of src directory ( see #1269 ) :

| Old name | New name |
|-|-|
| de-CH | de_CH |
| pt-BR | pt_BR |
| sr-cyrillic | sr_Cyrillic |
| sr-latin | sr_Latin |
| uz-cyrillic | uz_Cyrillic |
| uz-latin | uz_Latin |
| zh-CN | zh_CN |
| zh-HK | zh_HK |
| zh-TW | zh_TW |

Regards,

caouecs

#### Projects based on this package

* [x] [LaravelLang](https://github.com/ARCANEDEV/LaravelLang) by @arcanedev-maroc  - Translations manager and checker for Laravel.
* [x] [Laravel-lang](https://github.com/overtrue/laravel-lang) by @overtrue  - Command to add languages in your project.
* [x] [laravel-lang-publisher](https://github.com/andrey-helldar/laravel-lang-publisher) by @andrey-helldar  - Easy installation and update of translation files for your project.

**Comment by andrey-helldar** [comment]
Thanks for the info!

My package is ready for such changes 😊

**Comment by caouecs** [comment]
Maybe tomorrow, it's our national day in France ;)

**Comment by andrey-helldar** [comment]
My congratulations!
![image](https://user-images.githubusercontent.com/10347617/87297263-d4e2bf80-c510-11ea-8e19-3e9209a24032.png)

**Comment by andrey-helldar** [comment]
My package has been [updated](https://github.com/andrey-helldar/laravel-lang-publisher/releases/tag/v5.0.0) 😎

@arcanedev-maroc, @overtrue, guys it's your turn 🍻
