### ISSUE TITLE
WIP : L5 passwords

### ISSUE THREAD

**Issue by caouecs** [caouecs/Laravel-lang#323]
"sent" => "We have e-mailed your password reset link!",
"reset" => "Your password has been reset!"

Just in `laravel5` branch.

Status :

- [ ] Albanian
- [ ] Arabic
- [ ] Brazilian
- [ ] Bosnian
- [ ] Bulgarian
- [ ] Cambodian
- [ ] Catalan
- [x] Chinese
- [x] Chinese from Taiwan (zh-TW)
- [ ] Czech
- [ ] Danish
- [ ] Dutch
- [ ] Finnish
- [x] French
- [x] German
- [ ] Greek
- [ ] Hebrew
- [ ] Hungarian
- [x] Indonesian
- [ ] Italian
- [x] Japanese
- [ ] Korean
- [ ] Lithunian
- [ ] Macedonian
- [ ] Montenegrin
- [ ] Norwegian Bokmål
- [ ] Polish
- [ ] Portuguese
- [ ] Romanian
- [ ] Russian
- [ ] Serbian
- [ ] Slovak
- [ ] Spanish
- [ ] Swedish
- [ ] Thai
- [x] Traditional Chinese (Hong Kong)
- [ ] Turkish
- [ ] Vietnamese

**Comment by overtrue** [comment]
Zh-* No need to modify，Thanks!
