### ISSUE TITLE
Rename the repo and turn "laravel5" branch into "master"

### ISSUE THREAD

**Issue by grrnikos** [caouecs/Laravel-lang#328]
As Laravel 5 is now official and stable, it's probably the perfect time to make these tiny but important updates. Imho, a slightly different but simpler name such as "laralang", "laralangs" or "laravel-lang" would be even better. What's your thought?

**Comment by caouecs** [comment]
Hello,
this repository will be updated this week-end

**Comment by grrnikos** [comment]
Nice, thanks :+1:

**Comment by caouecs** [comment]
done, sorry for the delay
