### ISSUE TITLE
Automatic installation via Composer

### ISSUE THREAD

**Issue by amenk** [caouecs/Laravel-lang#352]
When installing via composer, all lang folders should be automatically copied to app/lang so updates of the repo via composer also reflect any changes.

**Comment by neomerx** [comment]
Auto update is not as good ides as it might look at first.
By design Laravel language files stores not only Laravel but user resources as well. Thus auto update for such files will lead to overwriting user strings.

**Comment by caouecs** [comment]
Hello,
I started a new project to manage languages in a project

**Comment by amenk** [comment]
Is this project already on GitHub?

**Comment by caouecs** [comment]
not yet

**Comment by neomerx** [comment]
IMHO it should migrate into tools like transifex.com or similar
It supports arrays in ```array( ... => ...)``` notation but not ```[]``` and nested arrays which requires some pre/post handling however it gives all the goodies of tracking and translation reuse

**Comment by kw-pr** [comment]
Maybe it is possible to make a laravel package for the translations:
http://laravel.com/docs/master/packages#translations

Not sure if that would work but worth a try.

**Comment by amenk** [comment]
Arn't packages for additional translations? Laravel-lang is replacing core translations.

**Comment by overtrue** [comment]
https://github.com/overtrue/laravel-lang :smile:

**Comment by kw-pr** [comment]
@overtrue exactly. That's what I am talking about. Awesome!

**Comment by overtrue** [comment]
@kw-pr Thanks!
