### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by amenk** [caouecs/Laravel-lang#365]
Loading composer repositories with package information
	Updating dependencies (including require-dev)
	  - Installing caouecs/laravel4-lang (dev-master 8cd5048)
	    Downloading: Connecting...    Failed to download caouecs/laravel4-lang from dist: The "https://api.github.com/repos/caouecs/Laravel4-lang/zipball/8cd50480137307b620d574804289f800e6b50246" file could not be downloaded (HTTP/1.1 404 Not Found)
	    Now trying to download from source

maybe you have to change the canonical setting on packagist?

https://packagist.org/packages/caouecs/laravel4-lang

It says https://github.com/caouecs/Laravel4-lang

**Comment by amenk** [comment]
Download from repo works though ... but it should also work from the dist / zipball

**Comment by amenk** [comment]
*bump*

**Comment by caouecs** [comment]
Hello,
sorry but I tried, and I don't have any problem : "caouecs/laravel4-lang": "~2.0"

**Comment by amenk** [comment]
did you install from source or from dist?

**Comment by amenk** [comment]
GitHub will make redirects in one of the next releases: https://developer.github.com/changes/2015-04-17-preview-repository-redirects/

**Comment by amenk** [comment]
Still I think the composer repo should be fixed. We currently can not install our projects properly :-(

**Comment by caouecs** [comment]
I'm sorry but I don't have your problem, so I can't help to fix it

**Comment by amenk** [comment]
It looks like it started working now. Can not reproduce it in a new project so I belive composer update will be enough.

Thank you.
