### ISSUE TITLE
Languages and countries translations

### ISSUE THREAD

**Issue by ronlobo** [caouecs/Laravel-lang#369]
Hey there,

What about languages and countries translations?

**Comment by caouecs** [comment]
Hello,
see https://github.com/caouecs/Laravel-lang/blob/master/Status.md

**Comment by ronlobo** [comment]
Well, this was meant to have translations of language and country names, not the status :rotating_light:

**Comment by caouecs** [comment]
This project is just for translations of Laravel

**Comment by ronlobo** [comment]
Ai, thanks :)
