### ISSUE TITLE
Wrong pt-BR translation at validation.php

### ISSUE THREAD

**Issue by brayansdt** [caouecs/Laravel-lang#376]
People, before everything, thanks a lot for your project, you helped me very much. :D
But the problem that I noticed is that in the line 75 in pt-BR/validation.php file should be like this:
"string"           => "O campo :attribute deve ser um texto.",
instead of that:
"string"           => "The :attribute must be a string.",
:)

**Comment by caouecs** [comment]
Hello,
the aim of this project is to translate files, so you can propose a PR with your work.

Thanks ;)
