### ISSUE TITLE
Split laravel-lang subdirectories in submodules

### ISSUE THREAD

**Issue by kneipp** [caouecs/Laravel-lang#413]
Hello :-)

I started a Laravel template to start my fresh projects: https://github.com/kneipp/brazilian-laravel-template/  and would be nice if can link /lang/pt-BR to Laravel-lang submodule.

Can be nice for someone else.

**Comment by caouecs** [comment]
Hello,
if I do it for Brazilian, I must do for all languages... or you can do a PR

**Comment by kneipp** [comment]
Hello, i guess we can do it for all languages, what do you think?

Can i start with portuguese PR?

**Comment by caouecs** [comment]
What is the benefit ?

**Comment by kneipp** [comment]
Reusability and modularity on your repo. 
People will choose language instead all of them, like composer.
