### ISSUE TITLE
en folder?

### ISSUE THREAD

**Issue by mendrinos** [caouecs/Laravel-lang#430]
What about adding the en language folder as well?

It looks like there are some custom validation attributes translations on other languages but not in english...

```
'attributes' => [
       "name" => "الاسم",
        "username" => "اسم المُستخدم",
        "email" => "البريد الالكتروني",
        "first_name" => "الاسم",
```

**Comment by repoman1** [comment]
Help

**Comment by mendrinos** [comment]
Just to clarify a bit further:

This line of code:
https://github.com/caouecs/Laravel-lang/blob/master/ar/validation.php#L108

Doesn't exist on the default laravel en folder..:
https://github.com/laravel/laravel/blob/master/resources/lang/en/validation.php#L108

**Comment by caouecs** [comment]
Hello,
the "en" folder is included in laravel/laravel project, not needed here

for the 'attributes' array, it was an evolution from laravel 4 to have basic words

**Comment by mendrinos** [comment]
so this means we have all the translations for these attributes but not in english?

**Comment by caouecs** [comment]
No, look others files
