### ISSUE TITLE
Laravel-Lang Management 

### ISSUE THREAD

**Issue by nicolaeturcan** [caouecs/Laravel-lang#431]
Hi Caouecs,

I have a doubt. Is it needed to copy the langs from /vendor/caouecs/laravel4-lang to /resources/lang in order to make them working? If so, how can I can update langs from my laravel 5.1 project when your ones get changed in vendor?

Thanks for your attention.

**Comment by overtrue** [comment]
@nicolaeturcan https://github.com/overtrue/laravel-lang :smile:

**Comment by nicolaeturcan** [comment]
@overtrue Thanks for your answer.

**Comment by overtrue** [comment]
@nicolaeturcan You are welcome. :monkey_face:
