### ISSUE TITLE
[Proposal] Improve Coding Style

### ISSUE THREAD

**Issue by billmn** [caouecs/Laravel-lang#460]
With few changes to ".php_cs" rules we can increase files readability like this:

![laravel-lang-cs-fix](https://cloud.githubusercontent.com/assets/779534/10904104/c25582be-8210-11e5-9741-4d8a15a26491.jpg)

This can also be automatically fixed using StyleCI (https://styleci.io/).
Thoughts?

**Comment by jbrooksuk** [comment]
:+1: for StyleCI ;)

**Comment by arcanedev-maroc** [comment]
Check the PR #469

**Comment by caouecs** [comment]
Hello,
the code is more readable, but it's dangerous when you add a new key, longer. All must be shifted...

**Comment by arcanedev-maroc** [comment]
Long string line : Yep.
Dangerous: Nope.

IMO, this is just a string it's not like a long method name + arguments, if statement or something that have a logic behind.

**Comment by caouecs** [comment]
Ok, but we must update .php_cs

**Comment by arcanedev-maroc** [comment]
Salut @caouecs,

How about .php_cs ? can you explain me/us what it does ?

**Comment by billmn** [comment]
Is a set of rules for php-vs-fixer. 
I can change this rules today or tomorrow

**Comment by arcanedev-maroc** [comment]
So this is for local dev by using it with CLI/IDE.

**Comment by caouecs** [comment]
Yes, but I prefer to do in local
