### ISSUE TITLE
[Suggestion] ARCANEDEV/LaravelLang package

### ISSUE THREAD

**Issue by arcanedev-maroc** [caouecs/Laravel-lang#463]
Salut Fred :+1:,

I've recently created a package [ARCANEDEV/LaravelLang](https://github.com/ARCANEDEV/LaravelLang) based on your package translations.

This package offer more functionalities than `overtrue/laravel-lang`.

**The main features are :**
  * Missing translations Checker.
  * Translations Publisher.
  * Well documented & IDE Friendly.
  * Well tested with maximum code quality.

I want you and other artisans to try it and having some feedbacks.

Cordialement,

Youness

**Comment by LukasMa** [comment]
Hi,
work great with Laravel 5.1.*.

**Comment by arcanedev-maroc** [comment]
Glad to hear that :+1:
