### ISSUE TITLE
Creating CONTRIBUTING.md

### ISSUE THREAD

**Issue by arcanedev-maroc** [caouecs/Laravel-lang#478]
It's useful to create a CONTRIBUTING.md and cleaning up the README.md :

  * Improved contributing guidelines.
  * Testing and stuff.
  * For more details : https://github.com/blog/1184-contributing-guidelines

Check [this CONTRIBUTING.md](https://github.com/thephpleague/skeleton/blob/master/CONTRIBUTING.md) and/or [this CONTRIBUTING.md](https://github.com/ARCANEDEV/LaravelLang/blob/master/CONTRIBUTING.md) for inspiration.

**Comment by caouecs** [comment]
see source.md

**Comment by arcanedev-maroc** [comment]
@caouecs 

Non, je parle pas des **contributeurs**, je parle **comment contribuer** à ce projet (les regles/étapes a suivre).

**Comment by caouecs** [comment]
C'est dans le readme

**Comment by arcanedev-maroc** [comment]
Est ce que t'as compris à ce que j'ai dis dans le 1er commentaire :confused: ?
