### ISSUE TITLE
Permissions for files

### ISSUE THREAD

**Issue by atomoc** [caouecs/Laravel-lang#481]
Rights to the files do not allow them to read laravel.

**Comment by caouecs** [comment]
Hello,
with this project, you must copy files in the good repository.

**Comment by atomoc** [comment]
Hello. Sorry, i don't understand you. I spent an hour on it to find out what the problem is. I would not want someone to have done the same.

**Comment by arcanedev-maroc** [comment]
Hi @atomoc, can you tell us more details about your issue ?

Try to follow these steps:

 * Download the latest version : https://github.com/caouecs/Laravel-lang/archive/master.zip.
 * Unzip the file and copy a specific locale folder (or all locales) to the laravel's lang folder.
   * For example : copy the `fr` folder to `your-laravel-project/resources/lang`.
 * You can test the lang by switching the default locale in `your-laravel-project/config/app.php`.
 * Enjoy :+1: 

If you want to use this package with composer, try these packages:
 * [arcanedev/laravel-lang](https://github.com/ARCANEDEV/LaravelLang).
 * [overtrue/laravel-lang](https://github.com/overtrue/laravel-lang).

**Comment by atomoc** [comment]
Thanks @arcanedev-maroc, it needs one more point:
* Assigning rights to files: chmod -R 755 resources/lang/ru

**Comment by arcanedev-maroc** [comment]
You're welcome :+1:
