### ISSUE TITLE
Transition package to non versioned package name

### ISSUE THREAD

**Issue by shakaran** [caouecs/Laravel-lang#496]
I see in the [README](https://github.com/caouecs/Laravel-lang/blob/master/README.md) that this package is installed for Laravel 5 as:

    composer require caouecs/laravel4-lang ~2.0

Probably for Laravel 5, it would be less confusing if you create or transition the package to *laravel-lang* without the "4" marking the version. That is:

    composer require caouecs/laravel-lang ~2.0

Since you can use milestones or tags supporting the 5.x or 6.x in future if available and it doesn't make sense keep the 4 in 5 versions or future versions. And actually you are using *Laravel-lang* currently as this repo name (probably it should be also *laravel-lang* without the capital uppercase letter).

Also this should be updated in [packagist](https://packagist.org/packages/caouecs/laravel4-lang)

I know that it is probably a tedious change and probably it is not neccessary, but it is important for keep the things cleaned in future versions too.

**Comment by caouecs** [comment]
Hello @shakaran,
it's in my todo ;)

**Comment by shakaran** [comment]
@caouecs Thanks! :+1:

**Comment by caouecs** [comment]
see #531
