### ISSUE TITLE
Danish validation language file UTF-8 Issue 

### ISSUE THREAD

**Issue by mansouralex** [caouecs/Laravel-lang#528]
I'm facing an issue with Danish validation file and I'm getting this exception for the email rule for example. 

Malformed UTF-8 characters, possibly incorrectly encoded

What should be the proper fix for this kind of issue?

Thanks.

**Comment by caouecs** [comment]
Hello,
I don't have any problem with the file. When you open the file in your ide, what is the encoding of file ?

**Comment by mansouralex** [comment]
Thanks for bringing it up - I changed the file encoding to UTF-8 and it works now.

**Comment by caouecs** [comment]
If you want you can update the danish file ;)

* distinct
* in_array
* present
* required_unless
* string
* timezone

**Comment by mansouralex** [comment]
I will be glad to do so, but I'm not danish language speaker. I'm building an application for a client from Denmark :)
