### ISSUE TITLE
Command for easy installation

### ISSUE THREAD

**Issue by ablunier** [caouecs/Laravel-lang#540]
Hi!

I made a small package to install language files from an artisan command on any Laravel project and it uses as source your repository :)

https://github.com/ablunier/laravel-lang-installer

Just wanted to inform about it, cheers!

**Comment by arcanedev-maroc** [comment]
You can also check this one: https://github.com/caouecs/Laravel-lang/issues/463

**Comment by caouecs** [comment]
I will add in Readme.md a list of tools which use this package
