### ISSUE TITLE
[Proposal] Add en files.

### ISSUE THREAD

**Issue by overtrue** [caouecs/Laravel-lang#546]
Hi, @caouecs , I am working on my package `overtrue/laravel-lang`, I want to make it lumen support. 

So, do you think is that alright?

**Comment by caouecs** [comment]
Hi,
lumen doesn't have language files since 5.2 version ;) and before, it's the same validation file.

**Comment by overtrue** [comment]
@caouecs No, the lang path of lumen is `vendor/laravel/lumen-framework/resources/lang` 😆 ，so, I will update my package to load it. Thanks.

**Comment by caouecs** [comment]
Ah !!! OK ;) But it's the same validation file, no ?

**Comment by overtrue** [comment]
@caouecs Yes, it is.

**Comment by overtrue** [comment]
@caouecs https://github.com/overtrue/laravel-lang
