### ISSUE TITLE
Not translated auth.php file comments of ru

### ISSUE THREAD

**Issue by Djasir** [caouecs/Laravel-lang#598]
Translation:
    /*
    |--------------------------------------------------------------------------
    | Языковые ресурсы аутентификации
    |--------------------------------------------------------------------------
    |
    | Следующие языковые ресурсы используются вовремя аутентификации для
    | различных сообщений которые мы должны вывести пользователю на экран.
    | Вы можете свободно изменять эти языковые ресурсы в соответствии
    | с требованиями вашего приложения.
    |
    */

**Comment by caouecs** [comment]
Hello,
can you do a pull request ?

Thanks

**Comment by Djasir** [comment]
Hello, i did it.
