### ISSUE TITLE
is it compatible with 5.4?

### ISSUE THREAD

**Issue by kiwo12345** [caouecs/Laravel-lang#657]

**Comment by caouecs** [comment]
Hello,
yes I think. But I don't test it

**Comment by sandervanhooft** [comment]
@caouecs  @kiwo12345 Have you tried it yet with Laravel 5.4?

If it works, I'd advise to include this as a comment in the readme. The Laravel 5.4 docs introduce a new localization/translation system, so at first glance I'd suspect it will not work. I'm probably wrong though :).

**Comment by caouecs** [comment]
@sandervanhooft this package is just a translation of existing files, so no problem ;)

**Comment by sandervanhooft** [comment]
Works indeed, thanks @caouecs !

**Comment by ctf0** [comment]
@caouecs maybe we can make a new branch just for the json type files introduced in the latest release ?

maybe even include a script to convert the php to json for easier maintenance.

**Comment by caouecs** [comment]
good idea
