### ISSUE TITLE
Letters capitalized

### ISSUE THREAD

**Issue by caouecs** [caouecs/Laravel-lang#700]
Since Laravel 5.2, we can define letters capitalized. A new branch has been created to add this feature : `capital_letters`.

* [x] ar
* [x] be
* [x] bg
* [ ] bn
* [x] bs
* [ ] ca
* [ ] cs
* [x] cy
* [ ] da
* [ ] de
* [x] el
* [ ] es
* [ ] et
* [ ] fa
* [x] fi
* [x] fr
* [ ] gl
* [x] he
* [ ] hi
* [x] hr
* [x] hu
* [x] id
* [x] is
* [ ] it
* [ ] ja
* [ ] ka
* [ ] kk
* [ ] km
* [ ] ko
* [x] lt
* [x] me
* [x] mk
* [x] mn
* [ ] ms
* [ ] nb
* [ ] ne
* [x] nl : #699 
* [ ] nn
* [ ] pl
* [x] pt
* [x] pt-BR
* [x] ro
* [x] ru
* [ ] sc
* [ ] sk
* [ ] sl
* [ ] sq
* [x] sr
* [ ] sv
* [x] sw
* [ ] tg
* [x] th
* [ ] tk
* [x] tl
* [ ] tr
* [x] uk
* [ ] ur
* [x] vi
* [x] zh-CN
* [x] zh-HK
* [x] zh-TW

**Comment by overtrue** [comment]
zh-* not needed

**Comment by ctf0** [comment]
[ar] is done

**Comment by caouecs** [comment]
Hello all, 
I think it's time to merge this feature in master, for a new version ( 4.x.x )
