### ISSUE TITLE
Idea of cli command tool

### ISSUE THREAD

**Issue by selmonal** [caouecs/Laravel-lang#749]
Sometimes i just need only Mongolian [mn] for my app. And no need of multi lang package in the composer. In this case laravel-lang cli tool would be very useful to me. See the scenerio below:

```
cd ~/projects/some-laravel-project
laravel-lang add mn
```

After this command [mn] lang files gonna copied to resources directory and app.locale config changed to mn.

laravel-lang should be installed globally. Then use it like the laravel-installer.

**Comment by caouecs** [comment]
See https://github.com/caouecs/Laravel-lang#projects-based-on-this-package

**Comment by andrey-helldar** [comment]
@selmonal use a package https://github.com/andrey-helldar/laravel-lang-publisher 😊
