### ISSUE TITLE
Validation changed in original source.

### ISSUE THREAD

**Issue by idhamperdameian** [caouecs/Laravel-lang#751]
I think you need to update it again, please look at original source [here](https://github.com/laravel/laravel/commit/90886732cf6df6d8694287c3f9d92496a4f1c61b#diff-9c04f727a922ad4f105b9ad764ec221d)
https://github.com/caouecs/Laravel-lang/blob/827aa1240855862582573495aa67b50835792bc5/script/en/validation.php#L44

**Comment by caouecs** [comment]
:'(

**Comment by idhamperdameian** [comment]
Headache?  😺

**Comment by caouecs** [comment]
I open a issue for all languages ( #752 )
