### ISSUE TITLE
How to use this with composer

### ISSUE THREAD

**Issue by Kyslik** [caouecs/Laravel-lang#843]
I was following the instructions and either I am blind or something is missing.

This repository has no service provider, so no Laravel magic is happening, do I have to manually copy the contents from `./vendor` to `resources/lang`?

**Comment by caouecs** [comment]
Hello,
the best is to use one of projects based on this package :

* [LaravelLang by ARCANEDEV](https://github.com/ARCANEDEV/LaravelLang)
* [Laravel-lang by overtrue](https://github.com/overtrue/laravel-lang)
* [laravel-lang-installer by ablunier](https://github.com/ablunier/laravel-lang-installer)
