### ISSUE TITLE
Json output when run composer update

### ISSUE THREAD

**Issue by mohamedsabil83** [caouecs/Laravel-lang#857]
After updating to the last version, new son file rendered when running `composer update` or any artisan command like `ide-helper:package` or `package:discover` like shown in this image.
![screenshot from 2018-07-06 13-50-35](https://user-images.githubusercontent.com/10126040/42375445-3b63c7dc-8124-11e8-8226-9801dcb00936.png)

**Comment by nickdekruijk** [comment]
Experiencing the same.
Removing vendor/caouecs/laravel-lang/src/fr/fr.json and vendor/caouecs/laravel-lang/src/de/de.json fixes it but it probably needs to be fixed in another way.

**Comment by mohamedsabil83** [comment]
Thanks, bro. As you said, it's just happened with **fr** and **de** but not others.

**Comment by nickdekruijk** [comment]
Must be because of commit #145b58b, de and fr are the only ones with .json files inside the folder

**Comment by mohamedsabil83** [comment]
That's weird. cause there is **ar.json** file too but not shown when installing the package. why just those two included when installing?
Hope someone fixes that.

**Comment by caouecs** [comment]
@mohamedsabil83 it's with versions, now you will have problem with ar.json, ru.json...

I think the simpler solution is to have a "json" directory outside "src" directory

**Comment by mohamedsabil83** [comment]
@caouecs yes it's stopped the terminal tracing. I tested like that:
- update to the last version **3.0.52** which cause that.
- create a new folder **json** outside **src**.
- move `src > de > de.json` and `src > fr > fr.json` to the new `json` folder.

now, any calling for artisan or composer didn't trace the content of json's files.

**Comment by caouecs** [comment]
I have done a new branch ["json"](https://github.com/caouecs/Laravel-lang/tree/json)

**Comment by caouecs** [comment]
it's ok for you with the branch "json" ?

**Comment by mohamedsabil83** [comment]
yes it's working fine without any tracing to terminal

**Comment by mohamedsabil83** [comment]
Thank you. Just upgrading and all work fine.
