### ISSUE TITLE
Installation instruction needs a hint.

### ISSUE THREAD

**Issue by Eugene-Melbourne** [caouecs/Laravel-lang#871]
Please help. It is not clear from instruction of how to make laravel goes into 
`"endor/caouecs/laravel-lang` instead of `resources\lang\`

**Comment by caouecs** [comment]
Hello,
you copy files which you want in resources/lang, or you can use a [package](
https://github.com/caouecs/Laravel-lang#projects-based-on-this-package) based on this project.
