### ISSUE TITLE
Doubt: Capital letter

### ISSUE THREAD

**Issue by pedrofurtado** [caouecs/Laravel-lang#886]
@caouecs I have a doubt. In README.md of project, there is a snippet like this:

> Since Laravel 5.2, we can define letters capitalized. A new branch has been created to add this feature : capital_letters.

I want to contribute with PR's, but I did not understand what exactly we have to do.

Thanks! :beers:

**Comment by caouecs** [comment]
Hello,
for the moment, nothing with this branch.
