### ISSUE TITLE
:min not working

### ISSUE THREAD

**Issue by gatno** [caouecs/Laravel-lang#938]
on german language file the :min placeholder is not working.

I got the following error-message on 'gt'=>'numeric': 
amount muss mindestens :min sein.

If i change laravel to english it's correct:
The amount must be greater than 5.

**Comment by caouecs** [comment]
Hello,
because in english, it's not ":min" but ":value".

Can you try with ":value" in german version ?

**Comment by gatno** [comment]
Hmm it's also :min in english.
Here is the Line:
[https://github.com/laravel/laravel/blob/master/resources/lang/en/validation.php#L86](https://github.com/laravel/laravel/blob/master/resources/lang/en/validation.php#L86)

**Comment by caouecs** [comment]
euh...

you wrote :  'gt'=>'numeric':

**Comment by gatno** [comment]
Yes, my fault. :see_no_evil:

**Comment by caouecs** [comment]
I update files with problem of :min, :max and :values
